name             'bootstrap'
version          '0.0.1'
description      'Installs/Configures cloudconductor'
license          'Apache v2.0'
maintainer       'TIS Inc.'
maintainer_email 'ccndctr@gmail.com'
supports         'centos', '= 6.5'

depends          'iptables'
depends          'yum-epel'
depends          'consul', '>= 0.4.2'
