source 'https://supermarket.getchef.com'

cookbook 'bootstrap', path: '/opt/cloudconductor/bootstrap'
cookbook 'iptables'
cookbook 'yum-epel'
cookbook 'serf', git: 'https://github.com/bbaugher/serf.git', tag: '0.7.0'
cookbook 'consul', git: 'https://github.com/johnbellone/consul-cookbook.git', tag: 'v0.7.1'
